-- ============================================================================
-- SafeGuard 360 — Operational Memory & Intelligence Schema
-- Run once in the Supabase SQL editor.
-- All statements are idempotent (safe to re-run).
-- ============================================================================

-- ── 1. Unified operational event log ────────────────────────────────────────
create table if not exists public.ops_events (
  id           uuid primary key default gen_random_uuid(),
  ts           timestamptz not null default now(),
  event_type   text not null,
  -- event_type values: 'feed_fetch' | 'notification_sent' | 'notification_failed'
  --   | 'retry' | 'api_call' | 'escalation' | 'ws_disconnect' | 'scan_run'
  --   | 'auth_check' | 'chaos_test' | 'anomaly_detected'
  endpoint     text,
  region       text,          -- ISO country code or region slug
  feed_id      text,
  duration_ms  integer,
  success      boolean,
  attempt      integer default 1,
  error_code   text,
  error_msg    text,
  metadata     jsonb,
  req_id       text           -- correlates with _logger.js reqId
);

create index if not exists idx_ops_events_ts           on public.ops_events (ts desc);
create index if not exists idx_ops_events_type_ts      on public.ops_events (event_type, ts desc);
create index if not exists idx_ops_events_feed_ts      on public.ops_events (feed_id, ts desc) where feed_id is not null;
create index if not exists idx_ops_events_region_ts    on public.ops_events (region, ts desc) where region is not null;
create index if not exists idx_ops_events_endpoint_ts  on public.ops_events (endpoint, ts desc) where endpoint is not null;

alter table public.ops_events enable row level security;
drop policy if exists "Service role full access" on public.ops_events;
create policy "Service role full access" on public.ops_events for all using (true) with check (true);

-- ── 2. Feed reliability scores (materialised by ops-analyze cron) ───────────
create table if not exists public.feed_reliability (
  feed_id            text primary key,
  feed_name          text,
  category           text,
  geography          text,
  success_count_24h  integer default 0,
  failure_count_24h  integer default 0,
  success_count_7d   integer default 0,
  failure_count_7d   integer default 0,
  last_success       timestamptz,
  last_failure       timestamptz,
  avg_latency_ms     integer,
  p95_latency_ms     integer,
  reliability_score  numeric(5,4),  -- 0.0000 to 1.0000
  baseline_score     numeric(5,4),  -- 30-day learned baseline
  baseline_sigma     numeric(5,4),  -- learned standard deviation
  status             text default 'unknown',
  -- status: 'healthy' | 'degraded' | 'failing' | 'recovering' | 'unknown'
  consecutive_failures integer default 0,
  updated_at         timestamptz default now()
);

alter table public.feed_reliability enable row level security;
drop policy if exists "Service role full access" on public.feed_reliability;
create policy "Service role full access" on public.feed_reliability for all using (true) with check (true);

-- ── 3. Notification delivery history ────────────────────────────────────────
create table if not exists public.notification_delivery (
  id                uuid primary key default gen_random_uuid(),
  ts                timestamptz not null default now(),
  channel           text not null,         -- 'email' | 'sms' | 'whatsapp'
  notification_type text,                  -- 'sos' | 'missed_checkin' | 'incident' | 'alert' | 'passport' | 'debrief' | 'briefing' | 'invite'
  recipient_hash    text,                  -- SHA-256 hash of email/phone — no PII stored
  region            text,
  success           boolean,
  attempt           integer default 1,
  duration_ms       integer,
  error_code        text,
  provider          text,                  -- 'resend' | 'twilio' | 'twilio_whatsapp'
  is_synthetic      boolean default false  -- true = generated by chaos-test / simulation
);

create index if not exists idx_notif_delivery_ts        on public.notification_delivery (ts desc);
create index if not exists idx_notif_delivery_channel   on public.notification_delivery (channel, ts desc);
create index if not exists idx_notif_delivery_type      on public.notification_delivery (notification_type, ts desc);
create index if not exists idx_notif_delivery_success   on public.notification_delivery (success, ts desc);

alter table public.notification_delivery enable row level security;
drop policy if exists "Service role full access" on public.notification_delivery;
create policy "Service role full access" on public.notification_delivery for all using (true) with check (true);

-- ── 4. Regional connectivity intelligence ───────────────────────────────────
create table if not exists public.regional_connectivity (
  region             text primary key,
  country            text,
  continent          text,
  success_count_24h  integer default 0,
  failure_count_24h  integer default 0,
  avg_latency_ms     integer,
  connectivity_score numeric(5,4),
  baseline_score     numeric(5,4),
  baseline_sigma     numeric(5,4),
  status             text default 'unknown',
  -- status: 'excellent' | 'good' | 'degraded' | 'critical' | 'blackout' | 'unknown'
  last_degraded      timestamptz,
  last_blackout      timestamptz,
  degradation_count  integer default 0,  -- times degraded in last 30d
  updated_at         timestamptz default now()
);

alter table public.regional_connectivity enable row level security;
drop policy if exists "Service role full access" on public.regional_connectivity;
create policy "Service role full access" on public.regional_connectivity for all using (true) with check (true);

-- ── 5. Detected operational anomalies ───────────────────────────────────────
create table if not exists public.ops_anomalies (
  id             uuid primary key default gen_random_uuid(),
  detected_at    timestamptz not null default now(),
  anomaly_type   text not null,
  -- types: 'feed_degradation' | 'feed_blackout' | 'notification_spike' | 'latency_spike'
  --   | 'escalation_failure' | 'ws_disconnect_spike' | 'regional_blackout'
  --   | 'regional_degradation' | 'api_latency_spike' | 'predictive_warning'
  severity       text not null,  -- 'critical' | 'high' | 'medium' | 'low'
  subject        text,           -- feed_id, region, endpoint name
  description    text,
  metrics        jsonb,
  predictive     boolean default false,  -- true = forward-looking warning
  resolved_at    timestamptz,
  acknowledged   boolean default false,
  acknowledged_by text,
  acknowledged_at timestamptz,
  auto_resolved  boolean default false
);

create index if not exists idx_ops_anomalies_detected    on public.ops_anomalies (detected_at desc);
create index if not exists idx_ops_anomalies_unresolved  on public.ops_anomalies (detected_at desc) where resolved_at is null;
create index if not exists idx_ops_anomalies_severity    on public.ops_anomalies (severity, detected_at desc);
create index if not exists idx_ops_anomalies_subject     on public.ops_anomalies (subject, anomaly_type) where resolved_at is null;

alter table public.ops_anomalies enable row level security;
drop policy if exists "Service role full access" on public.ops_anomalies;
create policy "Service role full access" on public.ops_anomalies for all using (true) with check (true);

-- ── 6. Escalation failure log ────────────────────────────────────────────────
create table if not exists public.escalation_failures (
  id                  uuid primary key default gen_random_uuid(),
  ts                  timestamptz not null default now(),
  escalation_type     text,  -- 'missed_checkin' | 'sos' | 'incident' | 'crisis_broadcast'
  trip_id             uuid,
  user_id             uuid,
  attempted_channels  text[],
  failed_channels     text[],
  contacts_attempted  integer default 0,
  contacts_reached    integer default 0,
  region              text,
  error_details       jsonb,
  is_synthetic        boolean default false
);

create index if not exists idx_escalation_failures_ts   on public.escalation_failures (ts desc);
create index if not exists idx_escalation_failures_type on public.escalation_failures (escalation_type, ts desc);

alter table public.escalation_failures enable row level security;
drop policy if exists "Service role full access" on public.escalation_failures;
create policy "Service role full access" on public.escalation_failures for all using (true) with check (true);

-- ── 7. WebSocket disconnect history ─────────────────────────────────────────
create table if not exists public.ws_disconnects (
  id           uuid primary key default gen_random_uuid(),
  ts           timestamptz not null default now(),
  page         text,        -- 'dashboard' | 'control-room'
  status       text,        -- 'CHANNEL_ERROR' | 'TIMED_OUT' | 'CLOSED'
  reconnected  boolean default false,
  reconnect_ms integer,     -- milliseconds to reconnect
  user_agent   text
);

create index if not exists idx_ws_disconnects_ts on public.ws_disconnects (ts desc);

alter table public.ws_disconnects enable row level security;
drop policy if exists "Service role full access" on public.ws_disconnects;
create policy "Service role full access" on public.ws_disconnects for all using (true) with check (true);

-- ── 8. Operational trend summaries (periodic snapshots) ─────────────────────
create table if not exists public.ops_trend_summaries (
  id             uuid primary key default gen_random_uuid(),
  generated_at   timestamptz not null default now(),
  period         text,         -- 'hourly' | 'daily' | 'weekly'
  period_start   timestamptz,
  period_end     timestamptz,
  health_score   integer,      -- 0–100 composite
  anomaly_count  integer,
  summary        jsonb,        -- full intelligence payload
  predictive_warnings jsonb    -- forward-looking issues
);

create index if not exists idx_ops_trend_ts on public.ops_trend_summaries (generated_at desc);

alter table public.ops_trend_summaries enable row level security;
drop policy if exists "Service role full access" on public.ops_trend_summaries;
create policy "Service role full access" on public.ops_trend_summaries for all using (true) with check (true);

-- ── Seed known regions for connectivity tracking ─────────────────────────────
insert into public.regional_connectivity (region, country, continent) values
  ('south-africa',    'South Africa',               'Africa'),
  ('nigeria',         'Nigeria',                    'Africa'),
  ('kenya',           'Kenya',                      'Africa'),
  ('ethiopia',        'Ethiopia',                   'Africa'),
  ('ghana',           'Ghana',                      'Africa'),
  ('tanzania',        'Tanzania',                   'Africa'),
  ('uganda',          'Uganda',                     'Africa'),
  ('mozambique',      'Mozambique',                 'Africa'),
  ('drc',             'Democratic Republic of the Congo', 'Africa'),
  ('somalia',         'Somalia',                    'Africa'),
  ('south-sudan',     'South Sudan',                'Africa'),
  ('sudan',           'Sudan',                      'Africa'),
  ('mali',            'Mali',                       'Africa'),
  ('burkina-faso',    'Burkina Faso',               'Africa'),
  ('niger',           'Niger',                      'Africa'),
  ('chad',            'Chad',                       'Africa'),
  ('cameroon',        'Cameroon',                   'Africa'),
  ('angola',          'Angola',                     'Africa'),
  ('zimbabwe',        'Zimbabwe',                   'Africa'),
  ('zambia',          'Zambia',                     'Africa'),
  ('egypt',           'Egypt',                      'Africa'),
  ('libya',           'Libya',                      'Africa'),
  ('uae',             'United Arab Emirates',       'Middle East'),
  ('saudi-arabia',    'Saudi Arabia',               'Middle East'),
  ('iraq',            'Iraq',                       'Middle East'),
  ('iran',            'Iran',                       'Middle East'),
  ('afghanistan',     'Afghanistan',                'Middle East'),
  ('yemen',           'Yemen',                      'Middle East'),
  ('syria',           'Syria',                      'Middle East'),
  ('lebanon',         'Lebanon',                    'Middle East'),
  ('pakistan',        'Pakistan',                   'Asia')
on conflict (region) do nothing;

-- ── Done ────────────────────────────────────────────────────────────────────
-- Tables created: ops_events, feed_reliability, notification_delivery,
--   regional_connectivity, ops_anomalies, escalation_failures,
--   ws_disconnects, ops_trend_summaries
