/**
 * _cityCountry.js
 * Canonical city → country lookup shared across all scan/alert endpoints.
 * Single source of truth — edit here, not in individual files.
 *
 * Previously duplicated in scan-all.js and trip-alert-scan.js (with diverging entries).
 */

export const CITY_COUNTRY = {
  // ── Africa ───────────────────────────────────────────────────────────────────
  'johannesburg': 'South Africa', 'cape town': 'South Africa', 'durban': 'South Africa',
  'pretoria': 'South Africa', 'port elizabeth': 'South Africa', 'bloemfontein': 'South Africa',
  'lagos': 'Nigeria', 'abuja': 'Nigeria', 'kano': 'Nigeria', 'ibadan': 'Nigeria',
  'nairobi': 'Kenya', 'mombasa': 'Kenya', 'kisumu': 'Kenya',
  'kampala': 'Uganda', 'dar es salaam': 'Tanzania', 'dodoma': 'Tanzania', 'zanzibar': 'Tanzania',
  'accra': 'Ghana', 'kumasi': 'Ghana',
  'addis ababa': 'Ethiopia', 'dire dawa': 'Ethiopia',
  'luanda': 'Angola', 'huambo': 'Angola',
  'kinshasa': 'Democratic Republic of the Congo', 'lubumbashi': 'Democratic Republic of the Congo',
  'goma': 'Democratic Republic of the Congo',
  'harare': 'Zimbabwe', 'bulawayo': 'Zimbabwe',
  'lusaka': 'Zambia', 'livingstone': 'Zambia',
  'lilongwe': 'Malawi', 'blantyre': 'Malawi',
  'maputo': 'Mozambique', 'beira': 'Mozambique',
  'antananarivo': 'Madagascar',
  'port louis': 'Mauritius',
  'dakar': 'Senegal', 'saint-louis': 'Senegal',
  'bamako': 'Mali',
  'ouagadougou': 'Burkina Faso',
  'niamey': 'Niger',
  'ndjamena': 'Chad',
  'yaounde': 'Cameroon', 'douala': 'Cameroon',
  'libreville': 'Gabon',
  'brazzaville': 'Republic of the Congo', 'pointe-noire': 'Republic of the Congo',
  'mogadishu': 'Somalia', 'hargeisa': 'Somalia',
  'juba': 'South Sudan', 'wau': 'South Sudan',
  'khartoum': 'Sudan', 'omdurman': 'Sudan',
  'asmara': 'Eritrea',
  'djibouti': 'Djibouti',
  'cairo': 'Egypt', 'alexandria': 'Egypt', 'giza': 'Egypt',
  'tripoli': 'Libya', 'benghazi': 'Libya',
  'tunis': 'Tunisia', 'sfax': 'Tunisia',
  'algiers': 'Algeria', 'oran': 'Algeria',
  'casablanca': 'Morocco', 'rabat': 'Morocco', 'marrakech': 'Morocco', 'fez': 'Morocco',
  'windhoek': 'Namibia',
  'gaborone': 'Botswana',
  'maseru': 'Lesotho',
  'mbabane': 'Eswatini',
  'monrovia': 'Liberia',
  'freetown': 'Sierra Leone',
  'conakry': 'Guinea',
  'bissau': 'Guinea-Bissau',
  'banjul': 'Gambia',
  'abidjan': 'Ivory Coast', 'yamoussoukro': 'Ivory Coast',
  'lome': 'Togo',
  'cotonou': 'Benin', 'porto-novo': 'Benin',
  'malabo': 'Equatorial Guinea',
  'sao tome': 'São Tomé and Príncipe',
  'bangui': 'Central African Republic',
  'kigali': 'Rwanda',
  'bujumbura': 'Burundi', 'gitega': 'Burundi',
  'moroni': 'Comoros',
  'victoria': 'Seychelles',
  'port sudan': 'Sudan',

  // ── Europe ───────────────────────────────────────────────────────────────────
  'london': 'United Kingdom', 'manchester': 'United Kingdom', 'birmingham': 'United Kingdom',
  'edinburgh': 'United Kingdom', 'glasgow': 'United Kingdom', 'belfast': 'United Kingdom',
  'paris': 'France', 'lyon': 'France', 'marseille': 'France', 'nice': 'France',
  'berlin': 'Germany', 'munich': 'Germany', 'frankfurt': 'Germany', 'hamburg': 'Germany',
  'cologne': 'Germany', 'düsseldorf': 'Germany',
  'amsterdam': 'Netherlands', 'rotterdam': 'Netherlands', 'the hague': 'Netherlands',
  'brussels': 'Belgium', 'antwerp': 'Belgium',
  'madrid': 'Spain', 'barcelona': 'Spain', 'seville': 'Spain', 'valencia': 'Spain',
  'lisbon': 'Portugal', 'porto': 'Portugal',
  'rome': 'Italy', 'milan': 'Italy', 'naples': 'Italy', 'turin': 'Italy', 'florence': 'Italy',
  'vienna': 'Austria',
  'zurich': 'Switzerland', 'geneva': 'Switzerland', 'bern': 'Switzerland',
  'stockholm': 'Sweden', 'gothenburg': 'Sweden',
  'oslo': 'Norway',
  'copenhagen': 'Denmark',
  'helsinki': 'Finland',
  'reykjavik': 'Iceland',
  'dublin': 'Ireland',
  'warsaw': 'Poland', 'krakow': 'Poland',
  'prague': 'Czech Republic',
  'budapest': 'Hungary',
  'bucharest': 'Romania', 'cluj-napoca': 'Romania',
  'sofia': 'Bulgaria',
  'athens': 'Greece', 'thessaloniki': 'Greece',
  'istanbul': 'Turkey', 'ankara': 'Turkey', 'izmir': 'Turkey',
  'moscow': 'Russia', 'saint petersburg': 'Russia', 'novosibirsk': 'Russia',
  'kyiv': 'Ukraine', 'kharkiv': 'Ukraine', 'lviv': 'Ukraine', 'odesa': 'Ukraine',
  'minsk': 'Belarus',
  'chisinau': 'Moldova',
  'belgrade': 'Serbia',
  'zagreb': 'Croatia',
  'sarajevo': 'Bosnia and Herzegovina',
  'podgorica': 'Montenegro',
  'tirana': 'Albania',
  'skopje': 'North Macedonia',
  'pristina': 'Kosovo',
  'ljubljana': 'Slovenia',
  'bratislava': 'Slovakia',
  'tallinn': 'Estonia', 'riga': 'Latvia', 'vilnius': 'Lithuania',
  'valletta': 'Malta',
  'nicosia': 'Cyprus',

  // ── Middle East ──────────────────────────────────────────────────────────────
  'dubai': 'United Arab Emirates', 'abu dhabi': 'United Arab Emirates', 'sharjah': 'United Arab Emirates',
  'riyadh': 'Saudi Arabia', 'jeddah': 'Saudi Arabia', 'mecca': 'Saudi Arabia', 'medina': 'Saudi Arabia',
  'doha': 'Qatar',
  'kuwait city': 'Kuwait',
  'muscat': 'Oman', 'salalah': 'Oman',
  'manama': 'Bahrain',
  'tehran': 'Iran', 'mashhad': 'Iran', 'isfahan': 'Iran', 'tabriz': 'Iran',
  'baghdad': 'Iraq', 'erbil': 'Iraq', 'basra': 'Iraq', 'mosul': 'Iraq',
  'beirut': 'Lebanon',
  'amman': 'Jordan', 'aqaba': 'Jordan',
  'tel aviv': 'Israel', 'jerusalem': 'Israel', 'haifa': 'Israel',
  'damascus': 'Syria', 'aleppo': 'Syria',
  'sanaa': 'Yemen', 'aden': 'Yemen',
  'kabul': 'Afghanistan', 'kandahar': 'Afghanistan', 'mazar-i-sharif': 'Afghanistan',

  // ── South & Southeast Asia ───────────────────────────────────────────────────
  'karachi': 'Pakistan', 'lahore': 'Pakistan', 'islamabad': 'Pakistan', 'peshawar': 'Pakistan',
  'mumbai': 'India', 'delhi': 'India', 'new delhi': 'India', 'bangalore': 'India',
  'chennai': 'India', 'kolkata': 'India', 'hyderabad': 'India', 'ahmedabad': 'India',
  'pune': 'India', 'surat': 'India', 'jaipur': 'India',
  'dhaka': 'Bangladesh', 'chittagong': 'Bangladesh',
  'colombo': 'Sri Lanka',
  'kathmandu': 'Nepal',
  'thimphu': 'Bhutan',
  'male': 'Maldives',
  'beijing': 'China', 'shanghai': 'China', 'shenzhen': 'China', 'guangzhou': 'China',
  'chengdu': 'China', 'xian': 'China', 'wuhan': 'China',
  'hong kong': 'Hong Kong',
  'macau': 'Macau',
  'taipei': 'Taiwan',
  'tokyo': 'Japan', 'osaka': 'Japan', 'kyoto': 'Japan', 'nagoya': 'Japan',
  'seoul': 'South Korea', 'busan': 'South Korea',
  'pyongyang': 'North Korea',
  'ulaanbaatar': 'Mongolia',
  'singapore': 'Singapore',
  'kuala lumpur': 'Malaysia', 'penang': 'Malaysia', 'kota kinabalu': 'Malaysia',
  'jakarta': 'Indonesia', 'bali': 'Indonesia', 'surabaya': 'Indonesia', 'medan': 'Indonesia',
  'manila': 'Philippines', 'cebu': 'Philippines', 'davao': 'Philippines',
  'bangkok': 'Thailand', 'chiang mai': 'Thailand', 'phuket': 'Thailand',
  'ho chi minh city': 'Vietnam', 'hanoi': 'Vietnam', 'da nang': 'Vietnam',
  'phnom penh': 'Cambodia', 'siem reap': 'Cambodia',
  'vientiane': 'Laos',
  'yangon': 'Myanmar', 'naypyidaw': 'Myanmar',
  'bandar seri begawan': 'Brunei',
  'dili': 'East Timor',

  // ── Oceania ──────────────────────────────────────────────────────────────────
  'sydney': 'Australia', 'melbourne': 'Australia', 'brisbane': 'Australia',
  'perth': 'Australia', 'adelaide': 'Australia', 'canberra': 'Australia',
  'auckland': 'New Zealand', 'wellington': 'New Zealand', 'christchurch': 'New Zealand',
  'port moresby': 'Papua New Guinea',
  'suva': 'Fiji',

  // ── Americas ─────────────────────────────────────────────────────────────────
  'new york': 'United States', 'los angeles': 'United States', 'chicago': 'United States',
  'houston': 'United States', 'miami': 'United States', 'washington': 'United States',
  'washington dc': 'United States', 'san francisco': 'United States',
  'seattle': 'United States', 'boston': 'United States', 'atlanta': 'United States',
  'dallas': 'United States', 'denver': 'United States', 'phoenix': 'United States',
  'toronto': 'Canada', 'montreal': 'Canada', 'vancouver': 'Canada', 'ottawa': 'Canada',
  'calgary': 'Canada',
  'mexico city': 'Mexico', 'guadalajara': 'Mexico', 'monterrey': 'Mexico',
  'bogota': 'Colombia', 'medellin': 'Colombia', 'cali': 'Colombia',
  'lima': 'Peru', 'cusco': 'Peru',
  'santiago': 'Chile',
  'buenos aires': 'Argentina', 'cordoba': 'Argentina',
  'sao paulo': 'Brazil', 'rio de janeiro': 'Brazil', 'brasilia': 'Brazil', 'salvador': 'Brazil',
  'caracas': 'Venezuela', 'maracaibo': 'Venezuela',
  'quito': 'Ecuador', 'guayaquil': 'Ecuador',
  'asuncion': 'Paraguay',
  'montevideo': 'Uruguay',
  'la paz': 'Bolivia', 'santa cruz': 'Bolivia',
  'panama city': 'Panama',
  'san jose': 'Costa Rica',
  'managua': 'Nicaragua',
  'tegucigalpa': 'Honduras',
  'san salvador': 'El Salvador',
  'guatemala city': 'Guatemala',
  'havana': 'Cuba',
  'santo domingo': 'Dominican Republic',
  'port-au-prince': 'Haiti',
  'kingston': 'Jamaica',
  'nassau': 'Bahamas',
  'bridgetown': 'Barbados',
  'port of spain': 'Trinidad and Tobago',
  'georgetown': 'Guyana',
  'paramaribo': 'Suriname',

  // ── Central Asia ─────────────────────────────────────────────────────────────
  'almaty': 'Kazakhstan', 'nur-sultan': 'Kazakhstan', 'astana': 'Kazakhstan',
  'tashkent': 'Uzbekistan', 'samarkand': 'Uzbekistan',
  'bishkek': 'Kyrgyzstan',
  'dushanbe': 'Tajikistan',
  'ashgabat': 'Turkmenistan',
  'baku': 'Azerbaijan',
  'yerevan': 'Armenia',
  'tbilisi': 'Georgia', 'batumi': 'Georgia',
}

/**
 * @param {string} city
 * @returns {string|null} — country name or null if not found
 */
export function cityToCountry(city) {
  if (!city) return null
  return CITY_COUNTRY[city.toLowerCase().trim()] || null
}
